### ISSUE TITLE
Where are the LISP codes mentioned here and how to let Emacs load them?

### ISSUE THREAD

**Issue by hongyi-zhao** [KaratasFurkan/.emacs.d#2]
You use the following init.el configuration:

https://github.com/KaratasFurkan/.emacs.d/blob/3dc457dd8cb99095812508034d7cd92cbba3af55/init.el#L2

But I can't find the "config.el" file in this repo at all. In addition, I also noticed that all your settings are stored in [README.org](https://github.com/KaratasFurkan/.emacs.d/blob/master/README.org). I still can't figure out how to let Emacs load these configurations this way.

Any hints will be highly appreciated.

Regards,
HY

**Comment by KaratasFurkan** [comment]
Check my [init.el](https://github.com/KaratasFurkan/.emacs.d/blob/master/init.el). It loads `README.org` or the `config.el` file generated by `README.org`. org-mode has **tangle** (export) feature, my config exports elisp codes to `config.el` automatically when I made a change.

**Comment by hongyi-zhao** [comment]
Thank you. I found the relevant introduction [here](https://orgmode.org/worg/org-contrib/babel/intro.html#literate-programming).
