### ISSUE TITLE
helm-posframe-border-color 

### ISSUE THREAD

**Issue by AtomicNess123** [KaratasFurkan/.emacs.d#3]
Is helm-posframe-border-color working currently?

**Comment by KaratasFurkan** [comment]
Yes it works. However, I don't update my packages frequently. If it didn't work for you, they ([helm-posframe](https://github.com/tumashu/helm-posframe), [posframe](https://github.com/tumashu/posframe)) may be updated with breaking changes.

You can find my package versions here: https://github.com/KaratasFurkan/.emacs.d/blob/master/straight/versions/default.el (the versions are actually commit IDs)
